- name: delete app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  #ignore_errors: yes

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory
 
# - name: download and extract code
#   ansible.builtin.unarchive:
#     src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
#     dest: "{{ app_location }}"
#     remote_src: yes

- name: download the artifact from nexus
  ansible.builtin.unarchive:
    src: "http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ appVersion }}/{{ component }}-{{ appVersion }}.zip"
    dest: "{{ app_location }}"
    remote_src: yes

#http://3.88.110.19:8081/repository/backend/com/expense/backend/1.1.0/backend-1.1.0.zip 